package cmd

import (
	"fmt"
	"strings"

	"github.com/alecthomas/kong"
)

func generateBash(parser *kong.Kong) string {
	var b strings.Builder

	b.WriteString(`#!/bin/bash
# bash completion for gccli
# Generated by gccli completion bash

_gccli_completions() {
    local cur prev words cword
    if type _init_completion &>/dev/null; then
        _init_completion || return
    else
        cur="${COMP_WORDS[COMP_CWORD]}"
        prev="${COMP_WORDS[COMP_CWORD-1]}"
        words=("${COMP_WORDS[@]}")
        cword=$COMP_CWORD
    fi

`)

	// Generate flag value completions (enum flags).
	rootFlags := collectFlags(parser.Model.Node)
	bashWriteEnumCases(&b, rootFlags, "")
	for _, cmd := range collectCommands(parser.Model.Node, nil) {
		node := findNode(parser.Model.Node, cmd.Path)
		if node == nil {
			continue
		}
		flags := collectFlags(node)
		bashWriteEnumCases(&b, flags, "")
	}

	// Generate command/subcommand completions based on current command path.
	b.WriteString("    # Determine the command path\n")
	b.WriteString("    local cmd_path=\"\"\n")
	b.WriteString("    for ((i=1; i < cword; i++)); do\n")
	b.WriteString("        case \"${words[i]}\" in\n")
	b.WriteString("            -*) ;;\n")
	b.WriteString("            *) cmd_path=\"${cmd_path} ${words[i]}\";;\n")
	b.WriteString("        esac\n")
	b.WriteString("    done\n")
	b.WriteString("    cmd_path=$(echo \"$cmd_path\" | xargs)\n\n")

	b.WriteString("    case \"$cmd_path\" in\n")

	// Root level.
	bashWriteCommandCase(&b, "", parser.Model.Node)

	// Subcommand levels.
	for _, cmd := range collectCommands(parser.Model.Node, nil) {
		node := findNode(parser.Model.Node, cmd.Path)
		if node == nil {
			continue
		}
		// Only write case if node has children (subcommands).
		hasSubcommands := false
		for _, child := range node.Children {
			if !child.Hidden && child.Type == kong.CommandNode {
				hasSubcommands = true
				break
			}
		}
		if hasSubcommands || len(collectFlags(node)) > 0 {
			bashWriteCommandCase(&b, strings.Join(cmd.Path, " "), node)
		}
	}

	b.WriteString("    esac\n")
	b.WriteString("}\n\n")
	b.WriteString("complete -F _gccli_completions gccli\n")

	return b.String()
}

func bashWriteEnumCases(b *strings.Builder, flags []flagInfo, prefix string) {
	for _, f := range flags {
		if len(f.Enum) == 0 {
			continue
		}
		fmt.Fprintf(b, "    if [[ \"$prev\" == \"--%s\"", f.Long)
		if f.Short != 0 {
			fmt.Fprintf(b, " || \"$prev\" == \"-%c\"", f.Short)
		}
		fmt.Fprintf(b, " ]]; then\n")
		fmt.Fprintf(b, "        COMPREPLY=($(compgen -W '%s' -- \"$cur\"))\n", strings.Join(f.Enum, " "))
		fmt.Fprintf(b, "        return\n")
		fmt.Fprintf(b, "    fi\n")
	}
}

func bashWriteCommandCase(b *strings.Builder, path string, node *kong.Node) {
	if path == "" {
		fmt.Fprintf(b, "        \"\")\n")
	} else {
		fmt.Fprintf(b, "        \"%s\")\n", path)
	}

	// Collect subcommands.
	var subCmds []string
	for _, child := range node.Children {
		if child.Hidden || child.Type != kong.CommandNode {
			continue
		}
		subCmds = append(subCmds, child.Name)
	}

	// Collect flags.
	var flagNames []string
	for _, f := range collectFlags(node) {
		flagNames = append(flagNames, "--"+f.Long)
		if f.Short != 0 {
			flagNames = append(flagNames, fmt.Sprintf("-%c", f.Short))
		}
	}
	all := append(subCmds, flagNames...)
	if len(all) > 0 {
		fmt.Fprintf(b, "            COMPREPLY=($(compgen -W '%s' -- \"$cur\"))\n", strings.Join(all, " "))
	}
	fmt.Fprintf(b, "            return\n")
	fmt.Fprintf(b, "            ;;\n")
}

// findNode walks the model tree to find the node at the given command path.
func findNode(root *kong.Node, path []string) *kong.Node {
	node := root
	for _, name := range path {
		found := false
		for _, child := range node.Children {
			if child.Name == name {
				node = child
				found = true
				break
			}
		}
		if !found {
			return nil
		}
	}
	return node
}
