package cmd

import (
	"fmt"
	"strings"

	"github.com/alecthomas/kong"
)

func generatePowerShell(parser *kong.Kong) string {
	var b strings.Builder

	b.WriteString("# PowerShell completion for gccli\n")
	b.WriteString("# Generated by gccli completion powershell\n\n")

	b.WriteString("Register-ArgumentCompleter -CommandName gccli -ScriptBlock {\n")
	b.WriteString("    param($wordToComplete, $commandAst, $cursorPosition)\n\n")
	b.WriteString("    $commands = $commandAst.CommandElements | Select-Object -Skip 1 | Where-Object { $_.ToString() -notlike '-*' } | ForEach-Object { $_.ToString() }\n")
	b.WriteString("    $cmdPath = ($commands -join ' ').Trim()\n")
	b.WriteString("    $flags = $commandAst.CommandElements | Where-Object { $_.ToString() -like '-*' } | ForEach-Object { $_.ToString() }\n")
	b.WriteString("    $lastFlag = $flags | Select-Object -Last 1\n\n")

	// Enum flag completions.
	b.WriteString("    # Complete enum flag values\n")
	psWriteEnumCompletions(&b, parser.Model.Node, "")

	b.WriteString("    # Complete commands and flags based on current path\n")
	b.WriteString("    switch ($cmdPath) {\n")

	// Root level.
	psWriteCommandSwitch(&b, "", parser.Model.Node)

	// Subcommand levels.
	for _, cmd := range collectCommands(parser.Model.Node, nil) {
		node := findNode(parser.Model.Node, cmd.Path)
		if node == nil {
			continue
		}
		psWriteCommandSwitch(&b, strings.Join(cmd.Path, " "), node)
	}

	b.WriteString("    }\n")
	b.WriteString("}\n")

	return b.String()
}

func psWriteEnumCompletions(b *strings.Builder, node *kong.Node, prefix string) {
	allFlags := collectFlags(node)
	for _, f := range allFlags {
		if len(f.Enum) == 0 {
			continue
		}
		fmt.Fprintf(b, "    if ($lastFlag -eq '--%s'", f.Long)
		if f.Short != 0 {
			fmt.Fprintf(b, " -or $lastFlag -eq '-%c'", f.Short)
		}
		fmt.Fprintf(b, ") {\n")
		for _, v := range f.Enum {
			fmt.Fprintf(b, "        [System.Management.Automation.CompletionResult]::new('%s', '%s', 'ParameterValue', '%s')\n",
				v, v, v)
		}
		fmt.Fprintf(b, "        return\n")
		fmt.Fprintf(b, "    }\n")
	}

	// Also check subcommand flags.
	for _, cmd := range collectCommands(node, nil) {
		childNode := findNode(node, cmd.Path)
		if childNode == nil {
			continue
		}
		for _, f := range collectFlags(childNode) {
			if len(f.Enum) == 0 {
				continue
			}
			fmt.Fprintf(b, "    if ($lastFlag -eq '--%s'", f.Long)
			if f.Short != 0 {
				fmt.Fprintf(b, " -or $lastFlag -eq '-%c'", f.Short)
			}
			fmt.Fprintf(b, ") {\n")
			for _, v := range f.Enum {
				fmt.Fprintf(b, "        [System.Management.Automation.CompletionResult]::new('%s', '%s', 'ParameterValue', '%s')\n",
					v, v, v)
			}
			fmt.Fprintf(b, "        return\n")
			fmt.Fprintf(b, "    }\n")
		}
	}
}

func psWriteCommandSwitch(b *strings.Builder, path string, node *kong.Node) {
	if path == "" {
		fmt.Fprintf(b, "        { $_ -eq '' -or $_ -eq $null } {\n")
	} else {
		fmt.Fprintf(b, "        '%s' {\n", path)
	}

	// Subcommands.
	for _, child := range node.Children {
		if child.Hidden || child.Type != kong.CommandNode {
			continue
		}
		help := escapePSString(child.Help)
		fmt.Fprintf(b, "            [System.Management.Automation.CompletionResult]::new('%s', '%s', 'ParameterValue', '%s')\n",
			child.Name, child.Name, help)
	}

	// Flags.
	for _, f := range collectFlags(node) {
		help := escapePSString(f.Help)
		fmt.Fprintf(b, "            [System.Management.Automation.CompletionResult]::new('--%s', '--%s', 'ParameterName', '%s')\n",
			f.Long, f.Long, help)
		if f.Short != 0 {
			fmt.Fprintf(b, "            [System.Management.Automation.CompletionResult]::new('-%c', '-%c', 'ParameterName', '%s')\n",
				f.Short, f.Short, help)
		}
	}

	fmt.Fprintf(b, "        }\n")
}

func escapePSString(s string) string {
	s = strings.ReplaceAll(s, "'", "''")
	return s
}
