package cmd

import (
	"fmt"
	"strings"

	"github.com/alecthomas/kong"
)

func generateFish(parser *kong.Kong) string {
	var b strings.Builder

	b.WriteString("# fish completion for gccli\n")
	b.WriteString("# Generated by gccli completion fish\n\n")

	// Root-level flags.
	for _, f := range collectFlags(parser.Model.Node) {
		fishWriteFlag(&b, f, "")
	}

	b.WriteString("\n")

	// Top-level commands (shown when no subcommand is active).
	for _, child := range parser.Model.Children {
		if child.Hidden || child.Type != kong.CommandNode {
			continue
		}
		help := escapeFishString(child.Help)
		fmt.Fprintf(&b, "complete -c gccli -f -n __fish_use_subcommand -a %s -d '%s'\n",
			child.Name, help)
	}

	b.WriteString("\n")

	// Subcommands and their flags.
	for _, cmd := range collectCommands(parser.Model.Node, nil) {
		node := findNode(parser.Model.Node, cmd.Path)
		if node == nil {
			continue
		}

		// Sub-subcommands.
		for _, child := range node.Children {
			if child.Hidden || child.Type != kong.CommandNode {
				continue
			}
			help := escapeFishString(child.Help)
			condition := fishCondition(cmd.Path)
			fmt.Fprintf(&b, "complete -c gccli -f -n '%s' -a %s -d '%s'\n",
				condition, child.Name, help)
		}

		// Flags for this command.
		for _, f := range collectFlags(node) {
			fishWriteFlag(&b, f, strings.Join(cmd.Path, " "))
		}
	}

	return b.String()
}

func fishWriteFlag(b *strings.Builder, f flagInfo, cmdPath string) {
	var condition string
	if cmdPath == "" {
		condition = ""
	} else {
		parts := strings.Fields(cmdPath)
		condition = fmt.Sprintf(" -n '%s'", fishCondition(parts))
	}

	help := escapeFishString(f.Help)

	var shortPart string
	if f.Short != 0 {
		shortPart = fmt.Sprintf(" -s %c", f.Short)
	}

	if len(f.Enum) > 0 {
		// Flag with enum values — use -r (requires argument) and -f (no file completion).
		fmt.Fprintf(b, "complete -c gccli -f%s%s -l %s -d '%s' -r -a '%s'\n",
			condition, shortPart, f.Long, help, strings.Join(f.Enum, " "))
	} else if f.IsBool {
		fmt.Fprintf(b, "complete -c gccli -f%s%s -l %s -d '%s'\n",
			condition, shortPart, f.Long, help)
	} else {
		fmt.Fprintf(b, "complete -c gccli -f%s%s -l %s -d '%s' -r\n",
			condition, shortPart, f.Long, help)
	}
}

func fishCondition(path []string) string {
	if len(path) == 0 {
		return "__fish_use_subcommand"
	}
	// Use __fish_seen_subcommand_from for the parent, and check the exact path.
	// For nested commands like "auth login", we check that "auth" was seen
	// and no deeper subcommand from auth's siblings is active.
	return fmt.Sprintf("__fish_seen_subcommand_from %s", strings.Join(path, "; and __fish_seen_subcommand_from "))
}

func escapeFishString(s string) string {
	s = strings.ReplaceAll(s, "'", "\\'")
	return s
}
