package cmd

import (
	"fmt"
	"strings"

	"github.com/alecthomas/kong"
)

func generateZsh(parser *kong.Kong) string {
	var b strings.Builder

	b.WriteString(`#compdef gccli
# zsh completion for gccli
# Generated by gccli completion zsh

_gccli() {
    local -a commands
    local curcontext="$curcontext" state line

`)

	// Write the root _arguments call.
	zshWriteFunction(&b, "_gccli", parser.Model.Node, true)

	// Write functions for subcommands.
	for _, cmd := range collectCommands(parser.Model.Node, nil) {
		node := findNode(parser.Model.Node, cmd.Path)
		if node == nil {
			continue
		}
		funcName := "_gccli_" + strings.Join(cmd.Path, "_")
		hasSubcommands := false
		for _, child := range node.Children {
			if !child.Hidden && child.Type == kong.CommandNode {
				hasSubcommands = true
				break
			}
		}
		if hasSubcommands {
			zshWriteFunction(&b, funcName, node, false)
		}
	}

	b.WriteString("_gccli \"$@\"\n")

	return b.String()
}

func zshWriteFunction(b *strings.Builder, funcName string, node *kong.Node, isRoot bool) {
	if !isRoot {
		fmt.Fprintf(b, "%s() {\n", funcName)
		b.WriteString("    local -a commands\n\n")
	}

	// Collect subcommands.
	var subCmds []struct {
		name string
		help string
	}
	for _, child := range node.Children {
		if child.Hidden || child.Type != kong.CommandNode {
			continue
		}
		subCmds = append(subCmds, struct {
			name string
			help string
		}{child.Name, child.Help})
	}

	if len(subCmds) > 0 {
		b.WriteString("    _arguments -C \\\n")

		// Flags.
		for _, f := range collectFlags(node) {
			zshWriteFlagArg(b, f)
		}

		b.WriteString("        '1:command:->command' \\\n")
		b.WriteString("        '*::arg:->args'\n\n")

		b.WriteString("    case $state in\n")
		b.WriteString("        command)\n")
		b.WriteString("            commands=(\n")
		for _, cmd := range subCmds {
			help := escapeZshDescription(cmd.help)
			fmt.Fprintf(b, "                '%s:%s'\n", cmd.name, help)
		}
		b.WriteString("            )\n")
		b.WriteString("            _describe 'command' commands\n")
		b.WriteString("            ;;\n")
		b.WriteString("        args)\n")
		b.WriteString("            case $line[1] in\n")
		for _, cmd := range subCmds {
			childNode := findNode(node, []string{cmd.name})
			if childNode == nil {
				continue
			}
			hasChildren := false
			for _, c := range childNode.Children {
				if !c.Hidden && c.Type == kong.CommandNode {
					hasChildren = true
					break
				}
			}
			if hasChildren {
				// Build full function name.
				var fullPath []string
				n := node
				// Walk up to build path (we only know the parent funcName).
				if isRoot {
					fullPath = []string{cmd.name}
				} else {
					// Extract path from funcName (strip _gccli_ prefix).
					prefix := strings.TrimPrefix(strings.TrimPrefix(funcName, "_gccli_"), "_gccli")
					if prefix != "" {
						fullPath = append(strings.Split(prefix, "_"), cmd.name)
					} else {
						fullPath = []string{cmd.name}
					}
				}
				_ = n
				childFunc := "_gccli_" + strings.Join(fullPath, "_")
				fmt.Fprintf(b, "                %s)\n", cmd.name)
				fmt.Fprintf(b, "                    %s\n", childFunc)
				fmt.Fprintf(b, "                    ;;\n")
			} else {
				// Leaf command — complete its flags.
				flags := collectFlags(childNode)
				if len(flags) > 0 {
					fmt.Fprintf(b, "                %s)\n", cmd.name)
					b.WriteString("                    _arguments \\\n")
					for _, f := range flags {
						zshWriteFlagArg(b, f)
					}
					b.WriteString("                        '*:filename:_files'\n")
					fmt.Fprintf(b, "                    ;;\n")
				}
			}
		}
		b.WriteString("            esac\n")
		b.WriteString("            ;;\n")
		b.WriteString("    esac\n")
	} else {
		// Leaf node — just flags.
		flags := collectFlags(node)
		if len(flags) > 0 {
			b.WriteString("    _arguments \\\n")
			for _, f := range flags {
				zshWriteFlagArg(b, f)
			}
			b.WriteString("        '*:filename:_files'\n")
		}
	}

	if !isRoot {
		b.WriteString("}\n\n")
	} else {
		b.WriteString("\n")
	}
}

func zshWriteFlagArg(b *strings.Builder, f flagInfo) {
	help := escapeZshDescription(f.Help)
	if len(f.Enum) > 0 {
		enumStr := strings.Join(f.Enum, " ")
		if f.Short != 0 {
			fmt.Fprintf(b, "        '(-%c --%s)'{-%c,--%s}'[%s]:value:(%s)' \\\n",
				f.Short, f.Long, f.Short, f.Long, help, enumStr)
		} else {
			fmt.Fprintf(b, "        '--%s[%s]:value:(%s)' \\\n", f.Long, help, enumStr)
		}
	} else if f.IsBool {
		if f.Short != 0 {
			fmt.Fprintf(b, "        '(-%c --%s)'{-%c,--%s}'[%s]' \\\n",
				f.Short, f.Long, f.Short, f.Long, help)
		} else {
			fmt.Fprintf(b, "        '--%s[%s]' \\\n", f.Long, help)
		}
	} else {
		if f.Short != 0 {
			fmt.Fprintf(b, "        '(-%c --%s)'{-%c,--%s}'[%s]:value:' \\\n",
				f.Short, f.Long, f.Short, f.Long, help)
		} else {
			fmt.Fprintf(b, "        '--%s[%s]:value:' \\\n", f.Long, help)
		}
	}
}

func escapeZshDescription(s string) string {
	s = strings.ReplaceAll(s, "[", "\\[")
	s = strings.ReplaceAll(s, "]", "\\]")
	s = strings.ReplaceAll(s, "'", "")
	s = strings.ReplaceAll(s, "\"", "")
	return s
}
