blank_issues_enabled: true
contact_links:
  - name: Questions
    url: https://github.com/bpauli/gccli/issues?q=is%3Aissue+label%3Aquestion
    about: Browse existing questions or open a new issue for general questions.
